services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - goofy-slider
      # - todo
      - cursum
      - moomin-chaser
      - tic-tac-toe

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # This entrypoint is for automatic renewals and is correct
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # This sysctl block is necessary to fix the IPv6 issue
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1

  goofy-slider:
    image: layor/goofy-slider:latest
    container_name: goofy_slider
    expose:
      - "5001"

  # todo:
  #   image: layor/todo:latest
  #   container_name: todo
  #   expose:
  #     - "5002"

  cursum:
    image: layor/cursum:latest
    container_name: cursum
    ports:
      - "5003:80"

  moomin-chaser:
    image: layor/moomin-chaser:latest
    container_name: moomin_chaser
    expose:
      - "5004"

  tic-tac-toe:
    image: layor/tic-tac-toe:latest
    container_name: tic_tac_toe
    expose:
      - "5005"
