# Generated by Django 4.2.7 on 2024-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSwipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='datasetentry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initial'), (1, 'Liked'), (2, 'Disliked'), (3, 'Undecided')], default=0),
        ),
    ]
